### ISSUE TITLE
[DOCS] Improve documentation of functions

### ISSUE THREAD

**Issue by matteobachetti** [xragua/xraybinaryorbit#2]
At the moment, one has the documentation printed when they execute the functions. However, one might want to know the parameters of the function _before_ executing them, for example, in a notebook:

<img width="874" alt="image" src="https://github.com/user-attachments/assets/9cd20ecf-4aeb-4cb4-815a-3ddac83a677e">

The parameters are printed, but not explained to the user, and in particular when using single-letter variables, they can be difficult to understand.

The standard way is writing a docstring. Basically, the same content that is printed during execution should just be a standalone string right below the `def`, e.g.:

```
def doppler_orbit_theoretical(t, units="keV", show_plot=False, precision_for_phase=0.01):
    """Compute the Doppler variation expected from orbital movement given a time array in seconds.

    Parameters
    ----------
    t: array-like
        Time array in seconds.

    Other parameters
    ----------------
    units: str, optional
        Units for the output. Default is "keV". Can be "keV", "s", or "angstrom".
    show_plot: bool, optional
        If True, a plot of the orbit and Doppler evolution is shown and saved. Default is False.
    precision_for_phase: float, optional
        Precision for phase calculation. Default is 0.01.

    Returns
    -------
    t: array-like
         Input time array.
    x: array-like
        Orbital phase array.
    equation: array-like
        Expected Doppler variation.

    """
```
Note that in this example I also formatted the docstring following the [`numpydoc` standard](https://numpydoc.readthedocs.io/en/latest/format.html). This is not required, but it is the standard used by Astropy and it works very well with sphinx for automatic documentation.

**Comment by xragua** [comment]
I have revised the documentation to follow the NumPy docstring standard, as suggested. I will keep the issue open until you have had a chance to review the changes and confirm that everything is in order. Thank you very much!

**Comment by matteobachetti** [comment]
Thanks @xragua! Following up: many of the functions in the code are not documented at all. Typically, user-facing API (functions that the users are supposed to use) should all be documented, while for private functions it's less of an obligation. However, private functions should be signaled (e.g., with a _leading_ underscore). In my opinion, private functions should also be documented, at least for the maintainer's sake, unless their working is obvious and their code is really simple. Coming back to the code you wrote in three years, you need to be able to still understand what a function exactly does.

**Comment by xragua** [comment]
Dear @matteobachetti, I completely agree. Now, I added docstrings in every function and also add a leading underscore to those that are private. Thanks!
