### ISSUE TITLE
[MNT] Test coverage and badges

### ISSUE THREAD

**Issue by matteobachetti** [xragua/xraybinaryorbit#9]
More of a recommendation than a requirement, but:

A convenient way to always have test coverage measurements is using https://about.codecov.io/ or similar services. They provide hooks to run coverage measurements each time you do tests through Github Actions (and point to the parts of the code that still have received no tests).

Codecov and many other services also provide convenient badges to show the health status of your code (see a good example here: https://github.com/astropy/astroquery), including coverage.

**Comment by xragua** [comment]
Thanks for the info, now I use codecov in my CI tests

**Comment by renecotyfanboy** [comment]
Hey! You can add some nice badges in your README.md as suggested by @matteobachetti 

Just paste and drop the following at the top of the file if you feel so : 

```
![Codecov](https://img.shields.io/codecov/c/github/xragua/xraybinaryorbit)

[![status](https://joss.theoj.org/papers/7f4fbc6a63adc4ba5a07bb340a4d7246/status.svg)](https://joss.theoj.org/papers/7f4fbc6a63adc4ba5a07bb340a4d7246)
```

Also, there are more badges/styles at https://shields.io/. This might be considered as aesthetic stuff, but in my case, it's reassuring to see this kind of thing when I'm exploring a repo.

**Comment by xragua** [comment]
@renecotyfanboy Thanks for the lines :) ! I already added them to the REAME file and are working well.
